// generated — do not edit — run: npm run generate:ha-services
// domains: input_boolean, input_number, light, climate, media_player, scene, switch
import type { Action } from '@ajclarkson/homerun';

export const Services = {
  media_player: {
    turn_on: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'turn_on', target }),
    turn_off: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'turn_off', target }),
    toggle: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'toggle', target }),
    volume_up: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'volume_up', target }),
    volume_down: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'volume_down', target }),
    media_play_pause: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'media_play_pause', target }),
    media_play: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'media_play', target }),
    media_pause: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'media_pause', target }),
    media_stop: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'media_stop', target }),
    media_next_track: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'media_next_track', target }),
    media_previous_track: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'media_previous_track', target }),
    clear_playlist: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'clear_playlist', target }),
    volume_set: (target: { entity_id: string }, data: { volume_level: number }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'volume_set', target, data: data as Record<string, unknown> }),
    volume_mute: (target: { entity_id: string }, data: { is_volume_muted: boolean }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'volume_mute', target, data: data as Record<string, unknown> }),
    media_seek: (target: { entity_id: string }, data: { seek_position: number }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'media_seek', target, data: data as Record<string, unknown> }),
    join: (target: { entity_id: string }, data: { group_members: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'join', target, data: data as Record<string, unknown> }),
    select_source: (target: { entity_id: string }, data: { source: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'select_source', target, data: data as Record<string, unknown> }),
    select_sound_mode: (target: { entity_id: string }, data?: { sound_mode?: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'select_sound_mode', target, data: data as Record<string, unknown> | undefined }),
    play_media: (target: { entity_id: string }, data: { media: string; enqueue?: string; announce?: boolean }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'play_media', target, data: data as Record<string, unknown> }),
    browse_media: (target: { entity_id: string }, data?: { media_content_type?: string; media_content_id?: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'browse_media', target, data: data as Record<string, unknown> | undefined }),
    search_media: (target: { entity_id: string }, data: { search_query: string; media_content_type?: string; media_content_id?: string; media_filter_classes?: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'search_media', target, data: data as Record<string, unknown> }),
    shuffle_set: (target: { entity_id: string }, data: { shuffle: boolean }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'shuffle_set', target, data: data as Record<string, unknown> }),
    unjoin: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'unjoin', target }),
    repeat_set: (target: { entity_id: string }, data: { repeat: string }): Action => ({ type: 'ha.call_service', domain: 'media_player', service: 'repeat_set', target, data: data as Record<string, unknown> }),
  },
  light: {
    turn_on: (target: { entity_id: string }, data?: { transition?: number; rgb_color?: [number, number, number]; color_temp_kelvin?: number; brightness_pct?: number; brightness_step_pct?: number; effect?: string; advanced_fields?: unknown }): Action => ({ type: 'ha.call_service', domain: 'light', service: 'turn_on', target, data: data as Record<string, unknown> | undefined }),
    turn_off: (target: { entity_id: string }, data?: { transition?: number; advanced_fields?: unknown }): Action => ({ type: 'ha.call_service', domain: 'light', service: 'turn_off', target, data: data as Record<string, unknown> | undefined }),
    toggle: (target: { entity_id: string }, data?: { transition?: number; rgb_color?: [number, number, number]; color_temp_kelvin?: number; brightness_pct?: number; effect?: string; advanced_fields?: unknown }): Action => ({ type: 'ha.call_service', domain: 'light', service: 'toggle', target, data: data as Record<string, unknown> | undefined }),
  },
  switch: {
    turn_off: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'switch', service: 'turn_off', target }),
    turn_on: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'switch', service: 'turn_on', target }),
    toggle: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'switch', service: 'toggle', target }),
  },
  scene: {
    reload: (): Action => ({ type: 'ha.call_service', domain: 'scene', service: 'reload' }),
    apply: (data: { entities: Record<string, unknown>; transition?: number }): Action => ({ type: 'ha.call_service', domain: 'scene', service: 'apply', data: data as Record<string, unknown> }),
    create: (data: { scene_id: string; entities?: Record<string, unknown>; snapshot_entities?: string }): Action => ({ type: 'ha.call_service', domain: 'scene', service: 'create', data: data as Record<string, unknown> }),
    delete: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'scene', service: 'delete', target }),
    turn_on: (target: { entity_id: string }, data?: { transition?: number }): Action => ({ type: 'ha.call_service', domain: 'scene', service: 'turn_on', target, data: data as Record<string, unknown> | undefined }),
  },
  input_boolean: {
    reload: (): Action => ({ type: 'ha.call_service', domain: 'input_boolean', service: 'reload' }),
    turn_on: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'input_boolean', service: 'turn_on', target }),
    turn_off: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'input_boolean', service: 'turn_off', target }),
    toggle: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'input_boolean', service: 'toggle', target }),
  },
  input_number: {
    reload: (): Action => ({ type: 'ha.call_service', domain: 'input_number', service: 'reload' }),
    set_value: (target: { entity_id: string }, data: { value: number }): Action => ({ type: 'ha.call_service', domain: 'input_number', service: 'set_value', target, data: data as Record<string, unknown> }),
    decrement: (target: { entity_id: string }, data?: { amount?: number }): Action => ({ type: 'ha.call_service', domain: 'input_number', service: 'decrement', target, data: data as Record<string, unknown> | undefined }),
    increment: (target: { entity_id: string }, data?: { amount?: number }): Action => ({ type: 'ha.call_service', domain: 'input_number', service: 'increment', target, data: data as Record<string, unknown> | undefined }),
    min: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'input_number', service: 'min', target }),
    max: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'input_number', service: 'max', target }),
  },
  climate: {
    turn_on: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'turn_on', target }),
    turn_off: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'turn_off', target }),
    toggle: (target: { entity_id: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'toggle', target }),
    set_hvac_mode: (target: { entity_id: string }, data?: { hvac_mode?: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'set_hvac_mode', target, data: data as Record<string, unknown> | undefined }),
    set_preset_mode: (target: { entity_id: string }, data: { preset_mode: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'set_preset_mode', target, data: data as Record<string, unknown> }),
    set_temperature: (target: { entity_id: string }, data?: { temperature?: number; target_temp_high?: number; target_temp_low?: number; hvac_mode?: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'set_temperature', target, data: data as Record<string, unknown> | undefined }),
    set_humidity: (target: { entity_id: string }, data: { humidity: number }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'set_humidity', target, data: data as Record<string, unknown> }),
    set_fan_mode: (target: { entity_id: string }, data: { fan_mode: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'set_fan_mode', target, data: data as Record<string, unknown> }),
    set_swing_mode: (target: { entity_id: string }, data: { swing_mode: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'set_swing_mode', target, data: data as Record<string, unknown> }),
    set_swing_horizontal_mode: (target: { entity_id: string }, data: { swing_horizontal_mode: string }): Action => ({ type: 'ha.call_service', domain: 'climate', service: 'set_swing_horizontal_mode', target, data: data as Record<string, unknown> }),
  },
};
